name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r backend/requirements.txt

      - name: Lint & Type
        run: |
          ruff check .
          black --check .
          isort --check-only .
          mypy .

      - name: Tests
        run: pytest -q

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          tags: cdgc-lite-api:ci
